# Description: Configuration file for the DeepFool attack

model: !include ../shared/model_config.yml
dataset: !include ./shared/dataset_config.yml
dataloader: 
  default: !include ../shared/dataloader_config.yml
device: !include ../shared/device_config.yml
attack_procedure: !include ./shared/attack_procedure_config.yml

# Attack Specific Configuration
attack_config: 
  num_classes: 10 # Number of classes in the dataset . Options: [cifar10: 10, mnist: 10]
  overshoot: 0.02 # Overshoot parameter for DeepFool attack. Defaults to 0.02.
  max_iterations: 50 # The maximum number of iterations to use for the attack. Defaults to 50.
