# Description: The configuration file for adversarial training.


adversarial_specific:
  # --- Target Model and Attack Configurations ---
  model: resnet18 # The model that will be trained.
  models: null # List of models used for generating adversarial examples.
  attacks: # List of attacks used for generating adversarial examples.
    - Attack1: # Name of the attack.
        config: path/to/attack1_config.yml # Path to the attack configuration file.

training: !include ../train_test/train_config.yml # Training configuration file.