# Description: Configuration file for the evaluation

model: !include ../shared/model_config.yml
dataset: !include ../attacks/shared/dataset_config.yml
dataloader: 
  default: !include ../shared/dataloader_config.yml
device: !include ../shared/device_config.yml

evaluation:
  attack:  
    name: # Name of the attack.
    config: # Path to the attack configuration file.
  evaluators: # list of strings
    - "attack_success_rate"
  target_models: #  
  save_results: true
  save_path: # Path to save the results
  save_filename: # Filename to save the results
