# Description: Configuration file for the evaluation
evaluation_config:
  attack:  
    name: "cw" # Name of the attack.
    config: "../attacks/cw_attack_config.yml" # Path to the attack configuration file.
  evaluators: # list of strings
    - "attack_success_rate"
  target_models: # needed to evaluate the transferability of the attack
    - name: "custom_model"
      config: "../shared/model_config.yml"