# Description: Configuration file for the evaluation

model: !include ../shared/model_config.yml
dataset: !include ./shared/dataset_config.yml
dataloader: 
  default: !include ../shared/dataloader_config.yml
device: !include ../shared/device_config.yml

evaluations:
  - AttackSuccessRate