# Description: Configuration file for training the model

model_name: resnet18
dataset_name: cifar10
epochs: 10
batch_size: 32
lr: 0.001
optimizer: adam
loss: cross_entropy
save: false
save_path: null
save_name: null
device: CPU
save_checkpoint: false
save_checkpoint_path: null
save_checkpoint_name: null
checkpoint_interval: 1
load_checkpoint: false
load_checkpoint_path: null
