# Description: Configuration file for training the model

# Model Configuration
model_name: resnet18

# Dataset Configuration
dataset_name: cifar10

# Training Configuration
epochs: 10
batch_size: 32
lr: 0.001
optimizer: adam
loss: cross_entropy

# Device Configuration
use_ddp: false # Whether to use multi-GPU training with DistributedDataParallel.

# Device Configuration SINGLE GPU ONLY
# This configuration is only for single GPU training. For multi-GPU training, use the next configuration.
device: CPU # Training device. Options: [CPU, CUDA, MPS] or specific GPU ID [cuda:0, cuda:1, ...]

# Device Configuration MULTI GPU ONLY
# This configuration is only for multi-GPU training. For single GPU training, use the previous configuration. Make sure to set use_ddp to True.
gpu_ids: null # List of GPU IDs to use for training. If null, uses all available GPUs.
pin_memory: True # Whether to pin memory for the dataloader.

# Model Saving Configurations
save: false
save_path: null
save_name: null

# Checkpoint Saving Configurations
save_checkpoint: false
save_checkpoint_path: null
save_checkpoint_name: null
checkpoint_interval: 1

# Checkpoint Loading Configurations
load_checkpoint: false
load_checkpoint_path: null
