# --- HuggingFace Dataset Configurations (Load splits approach) ---
dataset_name: huggingface
identifier: uoft-cs/cifar10
num_classes: 10
load_splits:
  - train
  - test
constructor_args:
  input_key: img
  target_key: label
train_dataset_path: null
test_dataset_path: null
preprocessing: !include ./preprocess_config.yml
