model:
  model_name: resnet18
  num_input_channels: 3
  num_classes: 10
  pretrained: true
  weights: IMAGENET1K_V1
  is_external: false
  random_seed:
  path_configs:
    model_arch_path:
    model_weights_path:
  norm_config:
    add_norm_layer: false
    norm_mean:
    - 0.5
    - 0.5
    - 0.5
    norm_std:
    - 0.5
    - 0.5
    - 0.5
dataset:
  dataset_name: cifar10
  num_classes: 10
  train_dataset_path:
  test_dataset_path:
  preprocessing:
    steps:
    - name: ToImage
      params:
    - name: ToDtype
      params:
        dtype: torch.float32
        scale: true
  download: true
dataloader:
  test:
    num_workers: 4
    shuffle: true
    drop_last: false
    pin_memory: true
    batch_size: 32
device:
  use_ddp: false
  processor: cpu
  gpu_ids:
testing:
  criterion: cross_entropy
  topk: 1
