from advsecurenet.models.CustomModels.CustomCifar10Model import CustomCifar10Model
from advsecurenet.models.CustomModels.CustomMnistModel import CustomMnistModel
from advsecurenet.models.CustomModels.CustomYolov5Model import CustomYolov5Model
