# Description: Configuration file for differential privacy training the model

# Inherits shared configurations
model: !include ../shared/huggingface_model_config.yml
dataset: !include ../shared/dataset_config.yml
dataloader:
  train: !include ../shared/dataloader_config.yml 
  test: !include ../shared/dataloader_config.yml
device: !include ../shared/device_config.yml
training: !include ../shared/differential_privacy_training_config.yml