name: Unit Tests and Style Checks

on:
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint pytest-mock pytest-cov
          pip install -e .

      - name: Test with pytest
        run: |
          pytest

      - name: Lint with pylint
        run: |
          pylint advsecurenet cli

  radon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Radon
        run: |
          python -m pip install --upgrade pip
          pip install radon

      - name: Run Radon and enforce complexity
        id: radon
        run: |
          radon cc -s -a . > radon_output.txt
          AVERAGE_COMPLEXITY=$(awk '/Average complexity/ {print $3}' radon_output.txt)
          if [ "$AVERAGE_COMPLEXITY" != "A" ]; then
            echo "Average complexity is not A. It is $AVERAGE_COMPLEXITY."
            exit 1
          fi
